---
title: "Takım: İnci Taneleri"
sidebar: false
---

MUY660-İş Analitiği dersi takım sayfamıza hoş geldiniz.

Bu sayfada analitik çalışmalarımızı paylaşıyoruz.

Lütfen faaliyetlerimizi görmek için bizi takipte kalın.

## Takım Üyeleri

1.  [Selim Ugras Fendoğlu](/takim/selimfendoglu.qmd)

2.  [Muhammed Emre Şendur](/takim/MuhammedEmreSENDUR.qmd)

3.  [Mehmet Ali Gündoğan](/takim/MehmetAliGundogan.qmd)

4.  [Berkalp Şimşek](/takim/berkalpSimsek.qmd)

5.  [İrem Avcı](/takim/IremAVCI.qmd)

## Proje Adı

MUY660-İş Analitiği İyileştirme Çalışmaları (Örnek)

## Proje Konusu

Örnek: Bu projede MUY660-İş Analitiği ders içeriğinin analitik yaklaşımlarla iyileştirilmesini hedefledik. Bu doğrultuda tüm üniversitelerdeki benzer derslerin verisini toplayarak bir veri seti oluşturduk. Analiz için ........ yöntemleri kullanarak, ....... çalışmaları yaptık. Sonuç olarak, MUY660-İş Analitiği dersinin dünyadaki tüm derslerden daha iyi olduğunu ve bu dersi aldığımız için çok mutlu olduğumuzu tespit ettik.

## Veri Seti Hakkında Özet Bilgi

## Sonuçlar

(Burada key takeaways verilmelidir. En az 3 en fazla 5 madde ile çarpıcı sonuçlar sunulmalıdır.)
